#!/bin/bash

awk -F : '{if ($5 == "OpenShift guest") {print $1, $6}}' /etc/passwd | {
    while read uuid dn
    do
        f="${dn}/.env/LD_PRELOAD"
        if ! [ -e $f ]
        then
            cat <<EOF > $f
export LD_PRELOAD='ksm-preload.so'
EOF
            restorecon $f
            runcon -u system_u -r system_r -t openshift_initrc_t -l s0-s0:c0.c1023 \
                /usr/sbin/oo-admin-ctl-gears restartgear $uuid
        fi
    done
}
