#!/bin/bash

GEARS=50
TIMEOUT=600

for i in `seq $GEARS`
do
    host=$( rhc app show -l "u${i}" -p none -a "a${i}" --timeout $TIMEOUT | grep 'SSH:' | awk '{ print $2 }' | cut -f 2 -d '@' )

    curl -s "http://${host}/"                 &>/dev/null
    curl -k -s "https://${host}/"             &>/dev/null
    curl -k -s "https://${host}/phpmyadmin/"  &>/dev/null
done
