#!/bin/bash

awk -F : '{if ($5 == "OpenShift guest") {print $1, $6}}' /etc/passwd | {
    while read uuid dn
    do
        f="${dn}/.env/LD_PRELOAD"
        if [ -e $f ]
        then
            rm -f $f
        fi
    done
}
