#!/bin/bash

GEARS=50
TIMEOUT=600

if ! [ -e /root/.ssh/config ]
then
    cat <<_EOF_ > /root/.ssh/config
Host *
    StrictHostKeyChecking no

_EOF_

    chmod 600 /root/.ssh/config
    restorecon /root/.ssh/config
fi


mkdir -p /root/kitchen


for i in `seq $GEARS`
do
    gitrepo=$( rhc app show -l "u${i}" -p none -a "a${i}" --timeout $TIMEOUT | grep 'Git URL:' | awk '{ print $3 }' )

    git clone "$gitrepo" /root/kitchen/a${i}
    ( cd /root/kitchen/a${i}; git remote add upstream -m master git://github.com/openshift/kitchensink-example.git )
    ( cd /root/kitchen/a${i}; git pull -s recursive -X theirs upstream master )
    ( cd /root/kitchen/a${i}; git push )

done

