#!/bin/bash

GEARS=50
TIMEOUT=600

INSTANCE=$(curl -s http://169.254.169.254/latest/meta-data/instance-id | cut -f 2 -d -)
for i in `seq $GEARS`
do
    yes | rhc app delete -l "u${i}" -p none -a "a${i}" --timeout $TIMEOUT

    yes | rhc domain delete -l "u${i}" -p none -n "n${i}i${INSTANCE}" --timeout $TIMEOUT

    [ -e STOP ] && break
done

