#!/bin/bash

F="/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-node-1.3.1/lib/openshift-origin-node/model/unix_user.rb"

[ -e "${F}.orig" ] && exit

patch "${F}" < unix_user.rb.diff

service mcollective restart
